services:
  - type: web
    name: smart-exam-generator
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/app.py
    envVars:
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
